"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const skynode_1 = require("@hanul/skynode");
const Layout_1 = __importDefault(require("./Layout"));
class Contest {
    constructor() {
        Layout_1.default.current.title = "개소리 경연 대회";
        Layout_1.default.current.content.append(this.container = (0, skynode_1.el)(".contest-view", (0, skynode_1.el)("header", (0, skynode_1.el)("h1", "Provincial Governor's Sound Contest Rules 🐶🎖💰"), (0, skynode_1.el)("p", "If you use more than five mates, you can submit candidates for Gaesori (if the contest is still accepting candidates). Example of Dojisound candidate: Bitcoin is mankind's biggest blunder. , DSC collects garbage.) The provincial governor's sound with the most votes is automatically posted on the main page of the web page. Mates used for candidate submission or voting cannot be used again in that vote.Dogesound competition is a dog sound contest that runs on the Clayton chain. If you use more than five mates, you can submit candidates for Gaesori. The provincial governor sound with the most votes is automatically posted on the main page of the web page. The mate you used can be used again next time. Submission or voting of provincial governor sound candidates does not affect mate ownership at all. (Example: Bitcoin is humanity's biggest blooper. Or any phrase that DSC would like)"), (0, skynode_1.el)(".warning", "* The submission or voting of provincial governor's sound candidates has no effect on mate ownership."), (0, skynode_1.el)("p", `
                The contest is always open 365 days a year. The contest consists of a total of three stages (receiving candidates, voting, and resting), and the status changes at regular time intervals. Candidates will be accepted every two weeks, 1 day (about 86,400 blocks), 1 day (about 86,400 blocks) for voting, and 12 days (about 1,036,800 blocks).

                The winner's provincial governor sound will be NFTed and delivered to the winner. Please check the NFT of the existing winners through the link below!
                `), (0, skynode_1.el)(".button-wrap", (0, skynode_1.el)("button", "The Winner's NFT"))), (0, skynode_1.el)("section", (0, skynode_1.el)("hr"), (0, skynode_1.el)("h2", "The winner of Dojisound 👑🚀✌️"), (0, skynode_1.el)("table", (0, skynode_1.el)("thead", (0, skynode_1.el)("tr", (0, skynode_1.el)("td.id", "#"), (0, skynode_1.el)("td.votes", "VOTES"), (0, skynode_1.el)("td.dogesound", "DOGESOUND"))), (0, skynode_1.el)("tbody", (0, skynode_1.el)("tr", (0, skynode_1.el)("td.id", "100"), (0, skynode_1.el)("td.votes", "39,344"), (0, skynode_1.el)("td.dogesound", "If your salary is less than your mate's, please vote here.")))), (0, skynode_1.el)(".pagination", (0, skynode_1.el)("a", "<<"), (0, skynode_1.el)("a", "<"), (0, skynode_1.el)("a.active", "1"), (0, skynode_1.el)("a", "2"), (0, skynode_1.el)("a", "3"), (0, skynode_1.el)("a", "4"), (0, skynode_1.el)("a", "5"), (0, skynode_1.el)("a", ">"), (0, skynode_1.el)("a", ">>")), (0, skynode_1.el)("hr"), (0, skynode_1.el)("h2", "Do Governor Sound Contest Status Board 🐶👍🎖"), (0, skynode_1.el)("section.status-board", (0, skynode_1.el)("img", { src: "/images/shared/img/dog.png" }), (0, skynode_1.el)("h3", "The voting for the 2nd contest is underway."), (0, skynode_1.el)(".caption", "121 blocks are left until the next stage."), (0, skynode_1.el)("p", "- Wallet Address: 0xBC4CA0EdA7647A8aB7C2061c2E118A18a936f13D\n- Number of mates you have: 3300.\n- Available mates: 110.\n* Relax! Participation in voting does not affect your ownership at all."), (0, skynode_1.el)(".submit-container", (0, skynode_1.el)(".input-container", (0, skynode_1.el)("input"), (0, skynode_1.el)("label", "Using that...")), (0, skynode_1.el)("button", "Let's vote."))), (0, skynode_1.el)("h3", "Voting Dojisound candidates in progress:"), (0, skynode_1.el)("table", (0, skynode_1.el)("thead", (0, skynode_1.el)("tr", (0, skynode_1.el)("td.action", "ACTION"), (0, skynode_1.el)("td.votes", "VOTES"), (0, skynode_1.el)("td.dogesound", "DOGESOUND"))), (0, skynode_1.el)("tbody", (0, skynode_1.el)("tr", (0, skynode_1.el)("td.action", (0, skynode_1.el)("input", { type: "checkbox" })), (0, skynode_1.el)("td.votes", "39,344"), (0, skynode_1.el)("td.dogesound", "If your salary is less than your mate's, please vote here.")))), (0, skynode_1.el)(".pagination", (0, skynode_1.el)("a", "<<"), (0, skynode_1.el)("a", "<"), (0, skynode_1.el)("a.active", "1"), (0, skynode_1.el)("a", "2"), (0, skynode_1.el)("a", "3"), (0, skynode_1.el)("a", "4"), (0, skynode_1.el)("a", "5"), (0, skynode_1.el)("a", ">"), (0, skynode_1.el)("a", ">>")))));
    }
    changeParams(params, uri) {
    }
    close() {
        this.container.delete();
    }
}
exports.default = Contest;
//# sourceMappingURL=Contest.js.map