import { DomNode, el } from "@hanul/skynode";
import { View, ViewParams } from "skyrouter";
import BMCSAlert from "../component/bmcs/BMCSAlert";
import BMCSCollapsibleItem from "../component/bmcs/BMCSCollapsibleItem";
import Layout from "./Layout";

export default class Bmcs implements View {
    private container: DomNode;

    constructor() {
        Layout.current.title = "Biased Mate Cycle Shop";
        Layout.current.content.append(this.container = el(".bmcs-view",
            el("header",
                el(".overlay"),
                el("section",
                    el("h1", "Welcome to Biased Mate Cycle Shop!"),
                    el("p", "Biased MAte Cycle Shop가 뭔가요? BMCS는 2021년 7월 9일에 발매된 한국 최초의 제너레이티브 NFT, 도지사운드클럽 메이트의 후속 이야기를 세계관으로 두고 있는 PFP 컬렉션입니다. DSC 운영팀은 최근 국내 최초의 제너레이티브 NFT라는 이유로 큰 인기를 얻게 된 메이트들이 인기에 취해 안일해지자, 이들을 일깨우기 위해 4가지의 극약 처방 NFT(물약으로 알려짐. 원제는 BIAS CARDS(를 에어드랍하였습니다. 물약을 메이트가 마시면 전기감전을 느끼게 되고(Biased) 고속 성장을 하여 어른이 되게 됩니다. 이렇게 어른이 된 메이트를 바이어스라고 부릅니다. 성장한 메이트, 바이어스들이 새로운 모험가들을 위한 자전거를 판매하는 상점 Biased Mate Cycle Shop을 연다는 것으로 BMCS의 이야기가 시작됩니다."),
                ),
            ),
            el("section",
                el("article",
                    el("h2", "BMCS를 이해하는 3개의 주요 키워드"),
                    new BMCSCollapsibleItem("1. 스트릿브랜드", "스트릿브랜드"),
                    new BMCSCollapsibleItem("2. 메타버스 범용 아바타", "BMCS는 브랜드 파워가 온라인, 오프라인 양쪽에서 빌딩되도록 기획되었습니다. 현재 많은 기업들이 메타버스 제작에 참여하고 있습니다. 이로 인해 메타버스 컨텐츠에 대한 수요가 높아지는 것에 발 맞추어 픽셀, 복셀 타입의 아바타를 BMCS NFT에 연동하여 제공합니다. 초기 메타버스 플랫폼들에게 아밭차 컨텐츠를 제공하여 커뮤니티 파워를 공유하고 활용치를 늘려가며, DSC/BMCS 커뮤니티 파워를 확장합니다. 픽셀, 복셀 양식ㅇ은 다수의 메타버스 플랫폼에서 저비용으로 호환을 가능케하면서도 오랜 사랑을 받고 있는 검증된 디지털 아트 양식입니다. 유행을 타지 않는 것도 장점입니다."),
                    new BMCSCollapsibleItem("3. 완전 온체인", "BMCS는 브랜드 파워가 온라인, 오프라인 양쪽에서 빌딩되도록 기획되었습니다. 현재 많은 기업들이 메타버스 제작에 참여하고 있습니다. 이로 인해 메타버스 컨텐츠에 대한 수요가 높아지는 것에 발 맞추어 픽셀, 복셀 타입의 아바타를 BMCS NFT에 연동하여 제공합니다. 초기 메타버스 플랫폼들에게 아밭차 컨텐츠를 제공하여 커뮤니티 파워를 공유하고 활용치를 늘려가며, DSC/BMCS 커뮤니티 파워를 확장합니다. 픽셀, 복셀 양식ㅇ은 다수의 메타버스 플랫폼에서 저비용ㅇ로 호환을 가능케하면서도 오랜 사랑을 받고 있는 검증된 디지털 아트 양식입니다. 유행을 타지 않는 것도 장점입니다."),
                ),
                el("hr"),
                el("article.biased-mate-container",
                    el("h2", "Biased Mate"),
                    el(".content",
                        el("img", { src: "/images/view/bmcs/mate1.png", alt: "mate" }),
                        el("img", { src: "/images/view/bmcs/mate2.png", alt: "mate" }),
                        el("img", { src: "/images/view/bmcs/mate3.png", alt: "mate" }),
                        el("img", { src: "/images/view/bmcs/mate4.png", alt: "mate" }),
                        el("img", { src: "/images/view/bmcs/mate5.png", alt: "mate" }),
                        el("img", { src: "/images/view/bmcs/mate6.png", alt: "mate" }),
                        el("img", { src: "/images/view/bmcs/mate7.png", alt: "mate" }),
                        el("img", { src: "/images/view/bmcs/mate8.png", alt: "mate" }),
                        el("img", { src: "/images/view/bmcs/mate9.png", alt: "mate" }),
                        el("img", { src: "/images/view/bmcs/mate10.png", alt: "mate" }),
                        el("img", { src: "/images/view/bmcs/mate11.png", alt: "mate" }),
                        el("img", { src: "/images/view/bmcs/mate12.png", alt: "mate" }),
                        el("img", { src: "/images/view/bmcs/mate13.png", alt: "mate" }),
                        el("img", { src: "/images/view/bmcs/mate14.png", alt: "mate" }),
                        el("img", { src: "/images/view/bmcs/mate15.png", alt: "mate" }),
                        el("img", { src: "/images/view/bmcs/mate16.png", alt: "mate" }),
                        el("img", { src: "/images/view/bmcs/mate17.png", alt: "mate" }),
                        el("img", { src: "/images/view/bmcs/mate18.png", alt: "mate" }),
                        el("img", { src: "/images/view/bmcs/mate19.png", alt: "mate" }),
                        el("img", { src: "/images/view/bmcs/mate20.png", alt: "mate" }),
                        el("img", { src: "/images/view/bmcs/mate21.png", alt: "mate" }),
                        el("img", { src: "/images/view/bmcs/mate22.png", alt: "mate" }),
                        el("img", { src: "/images/view/bmcs/mate23.png", alt: "mate" }),
                        el("img", { src: "/images/view/bmcs/mate24.png", alt: "mate" }),
                        el("img", { src: "/images/view/bmcs/mate25.png", alt: "mate" }),
                        el("img", { src: "/images/view/bmcs/mate26.png", alt: "mate" }),
                        el("img", { src: "/images/view/bmcs/mate27.png", alt: "mate" }),
                        el("img", { src: "/images/view/bmcs/mate28.png", alt: "mate" }),
                        el("img", { src: "/images/view/bmcs/mate29.png", alt: "mate" }),
                        el("img", { src: "/images/view/bmcs/mate30.png", alt: "mate" }),
                        el("img", { src: "/images/view/bmcs/mate31.png", alt: "mate" }),
                        el("img", { src: "/images/view/bmcs/mate32.png", alt: "mate" }),
                        el("img", { src: "/images/view/bmcs/mate33.png", alt: "mate" }),
                        el("img", { src: "/images/view/bmcs/mate34.png", alt: "mate" }),
                        el("img", { src: "/images/view/bmcs/mate35.png", alt: "mate" }),
                        el("img", { src: "/images/view/bmcs/mate36.png", alt: "mate" }),
                    ),
                ),
                el("hr"),
                el("article.vibe-container",
                    el("h2", "VIBE of AYIAS (MATES 회원용)"),
                    el("h3", "바이어스 카드덱 구성"),
                    el(".content",
                        el(".card",
                            el("img", { src: "/images/view/bmcs/vibe1.png", alt: "vibe" }),
                            el("h4", "루비 목걸이(전체 개수 중 약 80%)"),
                            el("p", "메이트의 바디 특성만을 이어 받고 나머지는 모두 바뀐 메이트인 비아를 생성하는데 사용됩니다."),
                        ),
                        el(".card",
                            el("img", { src: "/images/view/bmcs/vibe2.png", alt: "vibe" }),
                            el("h4", "사파이어 목걸이(전체 개수 중 약 20%)"),
                            el("p", "메이트의 바디, 헤어, 눈 부위 특성을 유지한 채 재해석된 메이트인 비아를 생성하는데 사용됩니다."),
                        ),
                        el(".card",
                            el("img", { src: "/images/view/bmcs/vibe3.png", alt: "vibe" }),
                            el("h4", "독약(전체 개수 중 약 1%)"),
                            el("p", "모든 특성이 바뀐 메이트, 뱀 형상의 비아를 얻는데 사용됩니다."),
                        ), el(".card",
                            el("img", { src: "/images/view/bmcs/vibe4.png", alt: "vibe" }),
                            el("h4", "심해수(전체 개수 중 0.1% 미만)"),
                            el("p", "모든 특성이 바뀐 메이트, 범고래 형상의 비아를 얻습니다."),
                        ),
                    ),
                    el(".warning-container",
                        el("h4", "용도"),
                        el("p", "채굴 및 거버넌스 기능은 없습니다.\n기존 메이트 V1에게 부여될 특권이었던 아이야스 픽셀 입장은 비아에게 이전되었습니다. 바이어스 카드를 에어드랍 받아, 보유하신 메이트와 합성하면 획득되는 비아로 여전히 입장이 가능한 것이니, 오해 없으시길 바랍니다."),
                    ),
                ),
                el("hr"),
                el("article.roadmap-container",
                    el("h2", "Roadmap"),
                    el("h3", "판매 진행률에 따라서, 운영팀은 아래 로드맵 항목들을 실행할 것입니다."),
                    el(".content",
                        el(".card", { click: () => { new BMCSAlert("000%\n 픽셀 아바타 제작", "픽셀 아바타 제작", "OK") } },
                            el("h4", "000%"),
                            el("p", "픽셀 아바타 제작 >"),
                        ),
                        el(".card",
                            el("h4", "000%"),
                            el("p", "경험치 시스템 CYCLE 개발 >"),
                        ),
                        el(".card",
                            el("h4", "010%"),
                            el("p", "온라인 머천트샵 BMCS 개발 >"),
                        ),
                        el(".card",
                            el("h4", "030%"),
                            el("p", "엔진 NFT 제작 >"),
                        ),
                        el(".card",
                            el("h4", "040%"),
                            el("p", "셀럽 콜라보 음원 NFT 제작 >"),
                        ),
                        el(".card",
                            el("h4", "050%"),
                            el("p", "메타버스 힙합 공연 >"),
                        ),
                        el(".card",
                            el("h4", "060%"),
                            el("p", "믹스 토큰 에어 드랍 >"),
                        ),
                        el(".card",
                            el("h4", "070%"),
                            el("p", "스트릿 브랜드로 상향 전환 개발 >"),
                        ),
                        el(".card",
                            el("h4", "080%"),
                            el("p", "복셀 아바타 제작 >"),
                        ),
                        el(".card",
                            el("h4", "080%"),
                            el("p", "클레이튼-이더리움 브릿지서비스 개발"),
                        ),
                        el(".card",
                            el("h4", "090%"),
                            el("p", "와인/위스키 주조"),
                        ),
                        el(".card",
                            el("h4", "100%"),
                            el("p", "플래그쉽 아지트 개발 >"),
                        ),
                        el(".card",
                            el("h4", "100%"),
                            el("p", "기부 및 파트너 커뮤니티 기여 활동 >"),
                        ),
                    ),
                    el("a", "로드맵 상세보기 >"),
                ),
                el("hr"),
                el("article.faq-container",
                    el("h2", "FAQ"),
                    new BMCSCollapsibleItem("민팅 일정은 어떻게 되나요?", "[민팅일정]\n확정권 대상자 세일 민팅 : 3월 17일 09:00 - 20:00\n300 Klay | 300개"),
                    new BMCSCollapsibleItem("카드 합성은 어떻게 하나요?", "바텐더 H-null에게 카드를 전달하면 물약을 만들어줍니다. 이때 민팅이 활성화됩니다."),
                    new BMCSCollapsibleItem("AIYAS PIXEL이 뭔가요?", "AIYAS는 DSC에서 개발중인 php nft의 픽셀 메타버스입니다"),
                    new BMCSCollapsibleItem("BMCS NFT 획득방법 및 총 발행량", "[BMCS는 최대 2만개까지 발행 가능한 완전-온체인 NFT 컬렉션입니다. \n00000 - 09999번 : 1만개, 세일 민팅을 통해 획득\n10000 - 19999번 : 1만개, 카드 합성을 통해 획득\n특별 에디션 수량 : 범고래 18개, 뱀 216개, 셀러브리티 8개 (셀럽 소장용)"),
                ),
                el("hr"),
                el("article.partnership-container",
                    el("h2", "PARTNERSHIP"),
                    el("h3", "DSC Lable"),
                    el(".content",
                        el("img", { src: "/images/view/bmcs/partnership1.png", alt: "partnership" }),
                        el("img", { src: "/images/view/bmcs/partnership2.png", alt: "partnership" }),
                        el("img", { src: "/images/view/bmcs/partnership3.png", alt: "partnership" }),
                        el("img", { src: "/images/view/bmcs/partnership4.png", alt: "partnership" }),
                        el("img", { src: "/images/view/bmcs/partnership5.png", alt: "partnership" }),
                        el("img", { src: "/images/view/bmcs/partnership6.png", alt: "partnership" }),
                    ),
                ),
            ),
        ))
    }


    public changeParams(params: ViewParams, uri: string): void {
    }

    public close(): void {
        this.container.delete();
    }
}
