/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { ITransferListener } from "../ITransferListener";

export class ITransferListener__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITransferListener {
    return new Contract(address, _abi, signerOrProvider) as ITransferListener;
  }
}

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "from",
        type: "address",
      },
      {
        name: "to",
        type: "address",
      },
      {
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "transfer",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];
